- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  remote_port: 17022
  vars:
    key_name: smeuser
    instance_type: t2.micro
    security_group: default
    image: ami-337be65c
    region: eu-central-1

  tasks:

      - name: Launch instance
        ec2:
          key_name: "{{ key_name }}"
          group: "{{ security_group }}"
          instance_type: "{{ instance_type }}"
          image: "{{ image }}"
          wait: true
          region: "{{ region }}"
          vpc_subnet_id: subnet-a017cadd
          assign_public_ip: yes
        register: ec2

#    - name: Add new instance to host group
#      add_host:
#       hostname: "{{ item.public_ip }}"
#        groupname: launched
#      with_items: "{{ ec2.instances }}"
#
#    - name: Wait for SSH to come up
#      wait_for:
#        host: "{{ item.public_dns_name }}"
#        port: 22
#        delay: 60
#        timeout: 320
#        state: started
#      with_items: "{{ ec2.instances }}"
